### ISSUE TITLE
Inconsistency in the number of sentences due to deleted tweets

### ISSUE THREAD

**Issue by murthyrudra** [microsoft/GLUECoS#2]
Hi, I have observed there were many tweets which were nor downloaded due to the tweets being deleted. Also, for some strange reason for some tasks the number of sentences were higher than the number reported in the paper (specifically for English-Spanish datasets). Please find the table comparing the statistics reported in the paper and the statistics obtained after downloading the data.

**English-Hindi**

|            Corpus           |     Sent (Train)    |                   |     Sent (Dev)    |                   |     Sent (Test)    |                   |
|:---------------------------:|:-------------------:|:-----------------:|:-----------------:|:-----------------:|:------------------:|:-----------------:|
|                             |         Paper       |     Downloaded    |        Paper      |     Downloaded    |        Paper       |     Downloaded    |
|     FIRE LID (D)            |             2631    |           2098    |            500    |            500    |             406    |            406    |
|     UD POS (D)              |             1384    |           1344    |            215    |            209    |             215    |            225    |
|     FG POS (R)              |             2104    |           2098    |            263    |            261    |             264    |            264    |
|     IIITH NER (R)           |             2467    |           2467    |            308    |            308    |             309    |            307    |
|     SAIL Sentiment   (R)    |            10080    |          10080    |           1260    |           1260    |            1261    |           1261    |

**English-Spanish**

|       Corpus      |     Sent (Train)    |                   |     Sent (Dev)    |                   |     Sent (Test)    |                   |
|:-----------------:|:-------------------:|:-----------------:|:-----------------:|:-----------------:|:------------------:|:-----------------:|
|                   |         Paper       |     Downloaded    |        Paper      |     Downloaded    |        Paper       |     Downloaded    |
|     EMNLP 2014    |            10259    |           7192    |           1140    |            824    |            3014    |           2981    |
|     Bangor POS    |             2192    |           2167    |            274    |            269    |             274    |            270    |
|     CALCS NER     |            27366    |          28381    |           3420    |           3537    |            3421    |           3577    |
|     Sentiment     |             1681    |           1851    |            211    |            231    |             211    |            232    |

Could the inconsistency in the dataset lead to unfair comparison of the results?

**Comment by ssitaram** [comment]
Hi Rudra, deleted tweets can cause inconsistencies in the numbers and may not lead to direct fair comparison, but unfortunately we cannot do much as we cannot store tweets. Due to this, we reran the benchmark on our models before adding to the leaderboard. So the numbers in the paper and the number of tweets you could download may not be exactly the same, but should be much more comparable to the results on the leaderboard. To slightly alleviate this issue, we will also mention on the leaderboard when the model was run.

**Comment by murthyrudra** [comment]
Thanks
