### ISSUE TITLE
QA_EN_HI: Missing prediction for 234 

### ISSUE THREAD

**Issue by murthyrudra** [microsoft/GLUECoS#30]
Hi, I followed the instructions provided in the README file to download the data. I did not encounter any errors during the downloading of the data. However, on testing I am getting the following message when I submit the results.

```
QA_EN_HI: Missing prediction for 234
Error. Either examples are missing or ids of instances are incorrect

```
Also, I did try downloading the data again but the error is same.

**Comment by Genius1237** [comment]
@murthyrudra Sorry for the delay. I cloned the repo in a fresh `python:3.6` container, installed the dependencies, ran the QA download script and then ran training for QA. My test set and predictions file have example 234. Could you try following these steps and let me know if it works? I suspect that the error may be with your python environment.

**Comment by murthyrudra** [comment]
Hi, Sorry for the late reply. The issue was with the python version, Thanks the error was resolved.
