### ISSUE TITLE
Tweet not found error

### ISSUE THREAD

**Issue by vibhavagarwal5** [microsoft/GLUECoS#33]
Hi, I'm trying to download the dataset but the twitter part is not downloading.. I'm getting the error `Tweet not found :: t_id 666613019510775808 :: Contact author for full data-set`. Not sure what exactly I'm doing wrong.

**Comment by Genius1237** [comment]
You can ignore this. It is just a warning that is displayed by the preprocessing script supplied by the authors of the original dataset. The downloading/preprocessing will still happen

**Comment by vibhavagarwal5** [comment]
Oh ok. Thanks.
