### ISSUE TITLE
Spacy versioning error for DrQA

### ISSUE THREAD

**Issue by IamAdiSri** [microsoft/GLUECoS#39]
It would be helpful for people if you could add to the readme file that spacy version 2.1.0 is required to run DrQA. This isn't mentioned on their repo either and the repository seems dead so it probably won't be updated there anyways. If one tries to run their script it installs spacy v3 which is incompatible with their code. I had to find out the correct spacy version by looking up the date at which their scripts were written and comparing it to version releases.

**Comment by Genius1237** [comment]
Could you open a PR with the change? I will merge it in

**Comment by Genius1237** [comment]
Fixed in #58
