### ISSUE TITLE
Add an option to specify the Azure region

### ISSUE THREAD

**Issue by rohanrajpal** [microsoft/GLUECoS#5]
The code breaks if we try to use the Azure translator from any region other than `southeastasia`. I have modified the code in my fork and would be happy to make a pull request :)
Here's the commit: https://github.com/rohanrajpal/GLUECoS/commit/89fa5c3745a7f3febd7f6c0614d00326b0c01082

**Comment by Genius1237** [comment]
Can you open a PR? I'll have a look and get it merged,
