### ISSUE TITLE
Trained Models

### ISSUE THREAD

**Issue by agarwalchaitanya** [microsoft/GLUECoS#68]
Are the trained models on each task available publicly? Is it possible for the authors to share them? Specifically, I'm looking for code-mixed NMT and LID.

TIA!

**Comment by Genius1237** [comment]
Nope. You can however look at the huggingface model hub [link](https://huggingface.co/models), and you'll find that some users have uploaded their own custom models trained on different code-mixed datasets.

**Comment by agarwalchaitanya** [comment]
> Nope. You can however look at the huggingface model hub [link](https://huggingface.co/models), and you'll find that some users have uploaded their own custom models trained on different code-mixed datasets.

I couldn't find anything substantial on hf. I'm thinking of retraining models anyway but can't find a named script for LID. Can you direct me to it? And I guess for NMT, you'd be using `fairseq`?

**Comment by Genius1237** [comment]
LID uses the `BertToken.py` script. You can see how to launch it and pass arguments to it in the `train_token.sh` file. For MT, we use a huggingface based script and this is there at `run_seq2seq.py`. This gets launched from `train_mt.sh`, so you can look at that for how to pass the arguments. All these above mentioned scripts are in the `Code` directory.
