### ISSUE TITLE
Getting "Tweet doesn't exist", "Contact author for complete dataset" using download.sh

### ISSUE THREAD

**Issue by goru001** [microsoft/GLUECoS#75]
Hi @ssitaram,

I was trying to get GLUECoS datasets but got multiple logs saying "Tweet doesn't exist", "Contact author for complete dataset", possibly because few tweets which were there in the dataset do not exist anymore. It'll be great if you can share what should we do in such scenarios as train/test datasets might not be same as required for evaluation?

Thanks,
Gaurav

**Comment by Genius1237** [comment]
All the tweets weren't available when we ran it too. That's a generic warming from the script we used. Don't think you have to worry

30 Mar 2022 06:51:02 Gaurav Arora ***@***.***>:
